### ISSUE TITLE
ISPAPI Backorder Module for blesta

### ISSUE THREAD

**Issue by domaingood** [hexonet/blesta-ispapi-registrar#80]
The ISPAPI Backorder Addon supports the following functions and features:

High Performance Drop-Catching Technology
Supports gTLDs: .ASIA .BIZ .CLUB .COM .INFO .MOBI .NET .ORG .PRO .TOP
Supports many Afilias, CentralNic, Donuts and Rightside TLDs
Supports ccTLDs: AG .BZ .CC .CH .CO .DE .FM .LC .LI .ME .MN .SC .TV .US .VC
Extra Commissions are Paid to Resellers for Successful Backorders
Backorders are Free to Place and the Backorder Fee is Paid Only on Successful Registration
Multiple Currencies Supported
Multi-lingual (available in English, German with more to come)
Includes a Backorder Domain Name Search Engine
Automatic Drop List Update
Auction Platform for Handling Multiple Backorders
Easy to Install and Operate

**Comment by papakai** [comment]
Dear @domaingood,

for now, we have no backorder module for Blesta available. Based on current work load and project plan, we cannot provide you nor an ETA for a blesta backorder module neither if we will realize this in future. Reason is simply that the customer demand for this is right now very low and we have a lot more important projects to cover. In addition the most of our customers are using whmcs and therefore we have to give that development higher priority.
As we are currently restructuring things, it could of course be that we have in near future better technical approaches to realize such things easier.

Sorry that we cannot provide you better news. Still, many thanks for getting in touch with us and bringing this request up to our attention. We can understand the need for this, but still we cannot work on this right now for the reasons given. We have added your request to our queue of improvement/extension ideas for blesta.

**Comment by papakai** [comment]
Just a little update about what is going on at HEXONET / CentralNic regarding 3rd-party Software Integrations and especially regarding Blesta. We will focus this year on technically revamp in-house to improve in direction of 3rd-party Software Integrations to make new Integrations easier for us and leading to less maintenance effort / support on our end. When covered this will allow us to faster react on customer requests and to offer our products and services where ever we notice customer demand. Just a matter of time. We were also in touch with Blesta to get natively shipped with their software. Still, regarding your request - nothing we can promise, just wanted to keep you a bit informed.
