### ISSUE TITLE
ISPAPI Pricing Importer Module for BLESTA

### ISSUE THREAD

**Issue by domaingood** [hexonet/blesta-ispapi-registrar#81]
The ISPAPI Pricing Importer module is able to quickly update a domain pricing list in a few steps.

This module supports the following functions and features:
The ISPAPI Pricing Importer add-on supports the following features:
*Load TLDs with prices through three possible ways *HEXONET costs *HEXONET Price Classes *Custom CSV file *Update existing extensions *Flexible performance of step-wise pricing imports *Support for different currencies *Bulk price update by using a factor or a fixed amount *Edition of prices individually *Supported fields: *TLD *Register/Transfer/Renew pricing *DNS Management *Email Forwarding *ID Protection *EPP Code *Currency

**Comment by tulsi91** [comment]
Hi,

ISPAPI Pricing Importer module is for WHMCS. 
If you have any questions please let us know.

**Comment by papakai** [comment]
Dear @domaingood,

for now, we have not pricing importer module for Blesta available. Based on current work load and project plan, we cannot provide you nor an ETA for a blesta pricing importer neither if we will realize this in future. Reason is simply that the customer demand for this is right now very low and we have a lot more important projects to cover. In addition the most of our customers are using whmcs and therefore we have to give that development higher priority.
As we are currently restructuring things, it could of course be that we have in near future better technical approaches to realize such things easier.

Sorry that we cannot provide you better news. Still, many thanks for getting in touch with us and bringing this request up to our attention. We can understand the need for this, but still we cannot work on this right now for the reasons given.
