### ISSUE TITLE
Domain Registration (.tv)

### ISSUE THREAD

**Issue by domaingood** [hexonet/blesta-ispapi-registrar#82]
Domain Registration (.tv)
I dont find it in Blesta Module Many EXT is missing for BLesta module

**Comment by tulsi91** [comment]
Hi @domaingood,

.TV TLD is supported by Blesta ISPAPI registrar module. Could you please provide more details on your issue? Are you not able to find the TLD during package creation?

Could you please also provide a list of missing TLDs?

**Comment by papakai** [comment]
Closing as of missing feedback. Feel free to follow-up with us to get this ticket re-opened.
