### ISSUE TITLE
.my Domain is missing

### ISSUE THREAD

**Issue by lamanrasmi** [hexonet/blesta-ispapi-registrar#86]
.my Domains all missing in blesta Package dropdown. In Hexonet dashboard its available to order. Can you please check. thanks

**Comment by papakai** [comment]
Hi @lamanrasmi,

thanks for reporting, we are working on a patch.
Our automated release process will close this issue and will inform you when this patch is released - expect this to happen soon.

Thanks so much,
Kai

**Comment by papakai** [comment]
Please upgrade to the newest release. I have created an internal follow-up ticket as a lot other TLDs are also missing - we will work on an improvement for this, promised.

**Comment by lamanrasmi** [comment]
cool. will the newly added domain tld also work in sandbox? or only certain domain only available for testing in sandbox mode?

**Comment by papakai** [comment]
Hi,

We suggest two have two systems set up in-house: a Test Environment connected to our OT&E system and your production system. This way you ensure not to struggle with different configurations when switching.
Still, at least .my is available in our OT&E System. But this is not the case for every TLD. Sometimes Registries even don't have a OT&E/sandbox environment.

Best
Kai
